# Navigation Links
#   To link a homepage section, use a hash `#` followed by the section ID.
#   The weight parameter defines the order that the links appear.

main:
  - name: Skills
    url: /#skills
    weight: 10
  - name: Experience
    url: /#experience
    weight: 20
  - name: Contact
    url: /#contact
    weight: 30
  - name: About
    url: /about/
    weight: 50
