title = "Steve Donaghy"
baseURL = "https://neokushan.github.io/"
languageCode = "en-us"

defaultContentLanguage = "en"
enableGitInfo = false
enableEmoji = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^WC_']
